#!/usr/bin/env ruby

require 'import_export'
require 'csv_importer'
require 'json_exporter'

I18n.enforce_available_locales = false
csv_importer = CSVImporter.new(input_file: File.expand_path('./data/input.csv'), header: 1)
json_exporter = JSONExporter.new(output_file: './output.json')
ImportExport.convert_data(importer: csv_importer, exporter: json_exporter)
